### ISSUE TITLE
Improve the performance of the storage adapter

### ISSUE THREAD

**Issue by bookchin** [Storj/core#143]
After a chat with @rvagg, I think it will be well worth switching LevelDOWN our for LevelDOWNHyper:

* https://github.com/level/leveldown-hyper
* http://hyperdex.org/performance/leveldb/

We should compare some performance benchmarks and offer a test version of core to roll out to farmers who wish to test with their existing shards databases.

**Comment by bookchin** [comment]
Just like LMDB, there doesn't seem to be any windows support for HyperLevelDB which unfortunately may be a dealbreaker since so many farmers run the Windows GUI.

**Comment by bookchin** [comment]
There is RocksDB, which may be worth investigating as well.

**Comment by bookchin** [comment]
And also Basho's LevelDB fork used in Riak: https://www.npmjs.com/package/leveldown-basho

**Comment by bookchin** [comment]
Looks like both basho's fork and rocksdb will compile on windows.

**Comment by bookchin** [comment]
Let's give the basho fork a try - I don't think rocks is what we want.

**Comment by 1credit** [comment]
Level DB appears not be be scaling well. Following the chat channels and from personal experience running Storj, there are several problems:

1) Loss of a single 2mb shard will result in invalidation of the entire database - potentially TBs gone. Loss of a shard should invalidate that contract, but not everything.

2) Excessive open files - reports of 10s of thousands of files being held open, possibly 100s of thousands. This is not sustainable on most host platforms without significant tweaking and may cause failure on those that just want to "plug and play". Overhead of course is significant.

3) Database maintenance (database compaction, expired file deletion, etc.) are reported to take excessive system resources and excessive time (one report of over 24 hours for 650GB of data).

I suggest that leveldb, although a reasonable first choice, is not proving itself appropriate for the long term. I understand switching would not be easy, and may in fact require wiping of all data and starting over, but that is why this is a Test Group.

Alternatively, simply announce the limitation and advise people not to share more than, say, 500GB per SYSTEM, in order to avoid resource limitations.

Please keep in mind that first and foremost is the need for the final production system to be stable, reliable, and worry free. That trumps most any other consideration or feature.

I would not presume to guess what a better solution would be, but will toss out something like MongoDB - which is designed to handle files, is free for commercial use, etc.

**Comment by bookchin** [comment]
The concerns are valid and there are a number of things we need to do to improve performance, however I maintain the position that LevelDB is the right choice for Storj for a few reasons:

* Embeddable and portable
* Cross platform
* Works on low end and underpowered hardware
* Flexible and can be improved at the application layer

I have pretty extensive experience with MongoDB and believe it to be a great database for many use cases. However it's incorrect to assume that it is "designed for files". Mongo is designed for BSON documents and is capped at 16mb per document. It has a lot of features that we don't need like advanced querying and aggregation, sharding, clustering, replication, etc. It's a behemoth when compared to LevelDB and using it would completely undermine the portability of Storj and its ability to run on low end hardware. 

We use MongoDB for the bridge and it makes sense there, storing user accounts, file pointers, auth tokens, contracts, etc. But it is not ideal for storing arbitrary raw buffers. 

The primary issues we are having with LevelDB are like you stated:

* Expensive compaction when size exceeds a threshold
* Corruption of entire database if a single level is destroyed
* Read/write locks during compaction, preventing or slowing down acceptance of consignments

I have what I believe to be a good start on solving these problems at the application layer but I am not ready to publish the proposal yet. I'll be speaking with the rest of the team today to validate the design and if we reach consensus, I will author a paper/specification and publish it here for community review.

**Comment by bookchin** [comment]
On a related note, but perhaps less important, we cannot reasonably expect farmers to deploy and manage a MongoDB in order to participate in the network.

**Comment by 1credit** [comment]
I fear you may have to choose between small platform support and telling users to limit their participation to 100-250GB per network.  But time will tell, hopefully you can get through all the known issues so we can find new things to fix.

**Comment by littleskunk** [comment]
I think the main problem of leveldb is this: http://docs.basho.com/riak/kv/2.1.4/setup/planning/backend/leveldb/#weaknesses

My node has 6 Levels and more than 300GB. I don't know the default cache size but at the end we have to deal with 1GB RAM setups as well. In my case a 1GB cache would be only 0.3%. Leveldb reports 200000 files. 600 can be hold in cache = the first 2 or 3 levels. -> Every time I receive an offer I need 3 - 4 seeks for one leveldb query. That is the main performance problem.

I have a stupid question. Why don't we use a file based storage. At the moment the shard hash is the unique key. We could use it as file name. Only one seek would be needed to load it. That should be faster even with a few TB.

**Comment by rvagg** [comment]
tbh I've never found anything particularly compelling in Basho's fork and I also haven't heard of anyone depending on leveldown-basho for anything interesting, possibly for similar reasons.

HyperLevelDB Windows support _may_ be possible by leveraging some of the work we did to get plain LevelDB working on Windows, if you have someone with some C++ experience you should check out the stuff in deps/leveldb/port-libuv/ in the leveldown repo as a starter. I'd be surprised if it was too hard to make it work.

As I mentioned to @bookchin, you should see if you can get @rescrv interested in the work you're doing here. He's responsible for HyperLevelDB but is also the most responsive and knowledgeable person I know on how LevelDB works and how to best apply it to various situations. I don't know how busy he is but he'd be a valuable brains trust to be able to engage with on this project.

**Comment by littleskunk** [comment]
The file based storage has one disatvantage. The 1GB cache of leveldb can hold new shards and update them without any seek and later they will be moved to higher leveles. The file based storage would be slow on updating new shards.

@bookchin Do you see any chance to change this line of code? https://github.com/Storj/core/blob/1a19c430943cf17d5be57ea4a5f851b1f997b9f0/lib/network/interfaces/farmer.js#L69
Most of the time leveldb will return an error because the shard doesn't exists. This query is very expensive. Any chance to do this without the expensive query?

As farmer I am thinking about removing this query. That would allow me to send OFFER message without high IO usage. The renter will select 10 out of 1000 farmer and ask them for a data channel. These 10 have to query there leveldb and could return an error to the renter if they already have that mirror shard. The renter would have to select another farmer. More work for the renter but 990 farmer would be happy with this solution.

**Comment by 1credit** [comment]
I'd also be very concerned with doing something like allocating 70% of system memory to leveldb.  If Storj starts eating that type of memory, it will be rejected as a "background" class service and only run on dedicated machines - which is not a prime objective.  It would also mean that only a single node could be run on a machine (scratch having more than 1 drive under Windows, or more than 1 node under linux).

Only problem with using shard hashes is that hashes are not guarenteed to be unique.  They are statistically likely to be unique, but not guarenteed to be.  e.g. if two shards contain identical data they should hash to the same value.  Think in terms of an uncompressed file full of binary 1s.   That would not be a problem for Storj if it refused to send the "same" hash number to node more than once - but I'm not possitive that is currently checked for.  e.g.  If the farmer node responded to a write request with "sorry, I already have that hash value".

**Comment by 1credit** [comment]
Reagrding the file based system being slow, I'd suggest having some faith in file system level caching that most systems do.  Reads are cached by most OS's, writes are not heavily cached for file system write integrity.   If LevelDB is heavily (1GB) caching writes, then we should expect serious corruption after any unclean shutdown (say someone just powering down their Windows box instead of doing a shutdown).

**Comment by littleskunk** [comment]
@1credit I was 4 minutes faster :D
Check that line of code. Your node will not send an OFFER if you already have that shard.

**Comment by rescrv** [comment]
LevelDB will not heavily cache writes.  If you are not doing synchronous writes, at most WriteBuffer MB will be lost in an unclean shutdown.  If you are doing synchronous writes, you'll (assuming an absence of LevelDB bugs) lose nothing.  Data that gets rearranged in the background gets fsync'd every 2MB.  This can cause problems on some filesystems (ext3/4 come to mind).

I would not allocate much space to the block cache in leveldb.  It's almost always better to give the memory to the page cache.  I've even seen some experiments where a 100% miss rate block cache worked well.  It largely comes down to your access pattern and concurrency.  The mutex in the default lru cache can become a point of contention.

I would not recommend porting HyperLevelDB to Windows unless you can take on the entire effort yourself.  I've always developed in a POSIX environment and cannot tell you what assumptions I've baked into the code that could hinder portability to Windows.  I also do not devote time to actively improving the code.

**Comment by bookchin** [comment]
FYI: I started working on [this](http://bookch.in/kfs/) (also [here](https://github.com/bookchin/kfs)) with @frdwrd and @pgerbes1 to address the primary problems we are having.

**Comment by bookchin** [comment]
KFS is ready to plug in. Will start next week.

**Comment by bookchin** [comment]
For reference here: https://github.com/bookchin/kfs/blob/master/doc/performance-testing.md

Perhaps of interest to @rvagg?
