### ISSUE TITLE
MAX CONCURRENT OFFERS abuse

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#154]
As farmer I would like to get as many contracts as possible. The last core version is coming with a new feature that can be abused. Every farmer has a MAX_CONCURRENT_OFFERS. Default is only 3.

My abuse:
Create a few renter nodes sending out fake contracts. Keep them open as long as possible. Don't send any response on the incoming offer messages. Let them timeout.

Start my own farmer with a renter black list to ignore the fake contracts. Send out offer to the valid contracts only.

Result: Only a few offer will hit the valid contracts. My farmer has a better chance to get them.

**Comment by super3** [comment]
So the malicious renter is sending out contracts. The farmers are trying to contact the malicious renter, but he is not responding. Overtime wouldn't the farmers wise up and blacklist the node id of the malicious renter? Overtime the malicious renter should have nobody to talk to because he/she would have pissed of all the farmers in its neighborhood. 

I think this is also partially solved by introducing farmer minions. Just because you have renter nodes spamming the network doesn't mean they are spamming the neighborhood I am currently in. By increasing the number of entry points, allows me to communicate to other parts of the network that are not being spam attacked currently.

**Comment by littleskunk** [comment]
The malicious renters are not realy spamming. They send out contracts like every other renter. The difference is only that the malicious renter will wait as long as possible and not sign the contract at the end. The farmer can't proof it. He will only get the answer `Contract not longer open for offer` but he has to wait a few seconds for that message.

Renter contracts are published in the complete network and not only in the neighborhood. Everyone will send offer messages to the malicious renter.

How would you like to blacklist the renter?

**Comment by super3** [comment]
So if there farmer gets tries to negotiate numerous contacts with that node id to no avail then it should simply blacklist it locally.

**Comment by littleskunk** [comment]
https://github.com/Storj/core/issues/250 -> bridge should send the contracts to the farmer close to shard hash.
The last core release 2.0.0 has implemented a timeout for the offer messages.

I could still setup a few fake nodes sending fake contracts but I don't think my own farmer will have any big advantage. The blocked nodes will relay me the contract PUBLISH but my offer will be to late. -> I can setup fake nodes but I can only send offers in time to shards hash close to my nodeID. I could as well farm like everyone else and would get more or less the same number of shards.

From my side solved. Everyone agree or did I miss something?

**Comment by bookchin** [comment]
@littleskunk :+1:

**Comment by littleskunk** [comment]
Sorry I have to reopen this. The reward calculation is not finished. As far as I understand the calculation is based on a few bridge servers. That rule is perfect for this issue. Lets start the fake bridge and send out shards. As long as I don't send a bridge report to storj the shards will not be paid. Lets implement a whitelist for my own farmer to get paid shards only.

**Comment by 1credit** [comment]
Thereby flooding everyone else with useless shards - nasty.  It would require a substantial upload bandwidth to make an impact, but with the growth of gigabit Google services, that is a lot smaller issue than it once was.

**Comment by littleskunk** [comment]
Upload the shard with a high mirror number. Lets say 100 (if that is possible). That way you have to upload the shard only once but it will be unpaid 100 times.

**Comment by 1credit** [comment]
Or, if there is no validation checks, 1,000,000 copies, at which point everyone will be busy mirroring invalid shards.

Is this ONLY a TGC issue since real contracts later will require real payments?  Either way, its classic in terms of somebody misbehaving, and believe me, once real money is involved, people will spend days or weeks looking for exploits.

**Comment by bookchin** [comment]
This is only an issue for TGC, once payments/audits are fully implemented each bridge will be individually responsible for issuing payments and failure to do so in accordance with the contract will nullify the contract and the shard will be dropped. Additionally there will be a local reputation score until distributed reputation is implemented so that bad the farmer will not accept contracts from the bad bridge again. 

For the time being a whitelist for contract acceptance can be added.

**Comment by 1credit** [comment]
Highly recommend coding fences around all critical value, such a copies being a value between 1 and 32 (or whatever is 1 step beyond reasonable).  I know that coding is cumbersome, especially if your providing feedback error messages - but believe it is critical to the long term health of the code base.  This applies to all parsed input fields from the GUI or config.json files as well (see GUI issue #314).

Believe I heard at the hangout that this coming week is predominately "bug fix" week.  Sounds like a good time to do the above...

**Comment by littleskunk** [comment]
At the moment the network looks very stable but an attack is still possible.

I attacked the network with a bad renter. I request shard uploads but refuse uploading the shard. The bridge send out contracts non stop. Farmer will send an OFFER but they will get a response in less than 3 seconds. Most of the time in less than 1 second.
Everything else is just a question of multiple threads. How many upload requests do I have to send to more or less shutdown the network?
At the end I will not upload one single shard. I don't need to pay for this attack. -> Not only a problem for TGC.

**Comment by bookchin** [comment]
Closing this since between bridge-layer user rate limiting (in progress) and the addition of TRUSTED_KEYS to core some time ago, I don't think this is a problem anymore
