### ISSUE TITLE
storjshare ingnore free diskspace an write until it is full if limit > free space

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/core#187]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/usr/local/lib
└─┬ storjshare-cli@4.0.3
  └── storj@1.2.6
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

I expect that storjshare stops farming if free diskspace is < 10GB, to keep system responsive.

### Actual Behavior

Disk limit work, but if more space is assign then exist, storjshare fill the disk up to last bit, and crash. In this case no shard will be reachable.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Set size limit more than disk space
2. Wait until disk is full

**Comment by bookchin** [comment]
My initial reaction to this is simply that the program does what is expected (what you tell it to do). If you tell the program to use X diskspace, then it will use X diskspace. 

However I realize that users will make this mistake. I don't think that this should be implemented in core, though. Since core is a library, I think it should behave exactly how it is told. The application layer should implement any validation rules or safety checks like this. 

Can you open this issue at storjshare-cli? I'm happy to implement the check there.

**Comment by BlackDuck888** [comment]
Ok i opened this issue at  storjshare-cli. Sure the program did what he was told, but storjshare did not run on dedicated servers, there are many other reasons that cause this fault.
