### ISSUE TITLE
Loosing one shard/db file result in unrecoverable state

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/core#188]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
┬ storjshare-cli@4.0.3
└── storj@1.2.6
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

If one file is lost, the db system should have a self healing process, which recover from this state.
     ######

### Actual Behavior

I deleted a shard to get some space (#187) to start the farmer with an lowered size limit. If one shard is missing the farmer will not work anymore.

```
OpenError: Corruption: 1345 missing files; e.g.: /mnt/disk1/17EAA_1/farmer.db/119581.ldb
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:119:34
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:3
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Delete a shard / ldb file
2. Try to start a farmer

**Comment by bookchin** [comment]
The problem here is that deleting one ldb file is not deleting a single shard. LevelDB compacts items into "levels" which contain multiple items. The way we store file shards in LevelDB involves splitting the shard into smaller bits and storing them those bits individually keyed by the hash + index. If you delete a ldb file, you are are likely deleting parts of multiple shards. 

Don't delete files from your farmer DB, as it is not reasonable to expect that you should be able to recover from an intentional corruption of a database.
