### ISSUE TITLE
Support NAT-PMP

### ISSUE THREAD

**Issue by bookchin** [storj/core#218]
This should hopefully cover a decent section of farmers who cannot punch out with UPnP.
- https://github.com/TooTallNate/node-nat-pmp

**Comment by littleskunk** [comment]
https://github.com/Storj/core/issues/215

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
