### ISSUE TITLE
CLI crash both on windows 2012 server and ubuntu 14.04

### ISSUE THREAD

**Issue by Scrappy79** [Storj/core#222]
### Package Versions

Replace the values below using the output from `npm list storj`.

C:\Users\Administrator
└── (empty)

npm ERR! code 1

C:\Users\Administrator>

I'm getting this output from windows and ubuntu. 

Replace the values below using the output from `node --version`.

v4.4.5

### Actual Behavior

The program crashes at some stage:
{"level":"warn","message":"dropping received late response to 38afa306ee37d1e80816d95054a5730ee4c88644","timestamp":"2016-06-28T22:47:37.235Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-06-28T22:47:37.235Z"}
C:\Users\Administrator\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\lib\network\protocol.js:199
    item.trees[contract.get('renter_id')] = params.audit_tree;
                       ^

TypeError: Cannot read property 'get' of undefined
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\lib\network\protocol.js:199:24
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\lib\manager.js:71:5
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\lib\storage\adapters\level\index.js:55:7
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\lib\storage\adapters\level\filestore.js:25:5
    at dispatchError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\node_modules\levelup\lib\util.js
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\storjshare-cli\node_modules\storj\node_modules\levelup\lib\levelup.js:222:14

C:\Users\Administrator>

### Steps to Reproduce

Just leave it working for a while. It can crash in a few minutes or hours.

**Comment by woodstockmerkle** [comment]
**# Current versions:**


storjshare-cli@4.0.4 /usr/local/lib/node_modules/storjshare-cli
+-- async@1.5.2
+-- colors@1.1.2
+-- bs58@3.0.0 (base-x@1.0.4)
+-- commander@2.9.0 (graceful-readlink@1.0.1)
+-- myspeed@1.0.2 (hat@0.0.3, ws@1.1.0, timer-stopwatch@0.2.0, noisegen@1.0.0)
+-- kad-logger-json@0.1.2 (readable-stream@2.1.4, chai@3.5.0)
+-- prompt@1.0.0 (revalidator@0.1.8, pkginfo@0.4.0, read@1.0.7, winston@2.1.1, utile@0.3.0)
+-- storj-telemetry-reporter@1.0.1 (json-stable-stringify@1.0.1, jsen@0.6.1, request@2.72.0)
+-- storj@1.3.1 (ms@0.7.1, merge@1.2.0, ip@1.1.3, knuth-shuffle@1.0.1, mime@1.3.4, mtree@0.0.1, through@2.3.8, bitcore-message@1.0.2, semver@5.1.0, node-uuid@1.4.7, json-stable-stringify@1.0.1, readable-stream@2.1.4, bitcore-ecies@1.0.1, ws@1.1.0, tmp@0.0.28, jsen@0.6.1, kad-quasar@0.1.3, portfinder@1.0.3, nat-upnp@1.0.2, levelup@1.3.2, request@2.72.0, kad@1.5.15, bitcore-lib@0.13.16, leveldown@1.4.6)
root@wn-storj-01x:~/bin# storjshare -V
StorjShare: 4.0.4
Core:       1.3.1
Protocol:   0.7.0



# **Crashlog Message**

{"level":"info","message":"handling storage consignment request from 0b9fc9f6eb999f8868264b195226f87a7bda2865","timestamp":"2016-06-29T00:35:16.179Z"}
/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/protocol.js:199
    item.trees[contract.get('renter_id')] = params.audit_tree;
                       ^

TypeError: Cannot read property 'get' of undefined
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/protocol.js:199:24
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/manager.js:71:5
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/index.js:56:7
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/filestore.js:25:5
    at dispatchError (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/util.js:64:35)
    at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:222:14



# **Steps to reproduce **

Leave it run for a while 

I have amassed ~200 gb, and this happens more frequently than the reports from other users

**Comment by bookchin** [comment]
Thanks. Looks like a simple null reference check will solve this. I'll issue a patch tomorrow.

**Comment by Puychack** [comment]
**# Package Versions**
bigminer@bigminer:~$ npm list storj -g
/usr/local/lib
└─┬ storjshare-cli@4.0.4
  └── storj@1.3.3
bigminer@bigminer:~$ storjshare --version
StorjShare: 4.0.4
Core:       1.3.3
Protocol:   0.7.0
bigminer@bigminer:~$ node --version
v4.4.4

**# Crashlog Message**
storj-1 {"level":"info","message":"handling storage consignment request from 1495a38adfec7117a2dc84135be8ea9612841a86","timestamp":"2016-06-29T07:55:59.930Z"}
storj-1 TypeError: Cannot read property 'get' of undefined
storj-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/network/protocol.js:199:24
storj-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/manager.js:71:5
storj-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/index.js:56:7
storj-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/lib/storage/adapters/level/filestore.js:25:5
storj-1     at dispatchError (/usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/util.js:64:35)
storj-1     at /usr/local/lib/node_modules/storjshare-cli/node_modules/storj/node_modules/levelup/lib/levelup.js:222:14

**# Actual Behavior**
Since I installed core 1.3.3 storjshare crashed every hour for 8 hours.
Since around 2AM, uptime doesn't go beyond 1 minute.

**Comment by lunokhod** [comment]
Same problem...

**Comment by bookchin** [comment]
@Th3van curious if you've upgraded your bridge servers to 0.9.3?

**Comment by Th3Van** [comment]
yup, I upgraded all 10 bridge servers to 0.9.3 at ~0200 (UTC) today.
And since i did that, the data flow has dropped alot.
![storj-vlan-day001](https://cloud.githubusercontent.com/assets/18688983/16452595/96d65eb4-3e09-11e6-96fe-a8761514746c.png)

**Comment by bookchin** [comment]
@Th3van awesome, that means I know the issue. Can you PM me on the community IRC with your config so I can verify and we can fix the issue? We are working on updating the bridge README to include the new information needed to run the bridge with multiple minions. 

In the meantime I will add the null check handling and issue a core patch to prevent crash.
