### ISSUE TITLE
Rework the character encoding parts of the hashing and audit generation

### ISSUE THREAD

**Issue by bookchin** [Storj/core#251]
The hash utilities return a hex string, but when used together they interpret as utf8. 

Also the audit generator converts the shard bytes to hex and hashes them the same way. This is a wart and makes things difficult to express and implement in other languages. 

Let's work with buffers only and leave character encoding to the user to solve this. Will require a protocol version bump, so let's do it sooner than later.

**Comment by NutterzUK** [comment]
This issue currently blocks my development on a java client library as I can't create the same merkle tree. This is because it seems a bit confusing what is converted to hex and when, and exactly what is hashed and when. This results in not being able to submit a challenge with a tree that the bridge project accepts (Without knowing precisely how this is working).
