### ISSUE TITLE
Attack vector? Vanity type generator for close nodeIDs

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#323]
By using a vanity typte generator I could generate close nodeIDs.

I have seen nodeIDs with a distance of 8 bits. The generator can generate closer nodeIDs in a few seconds.

Could that be used for any attack?

@1credit thank you for this idea.

**Comment by bookchin** [comment]
Yes, this is a known vector for Sybil and Eclipse attacks. An attacker could generate enough node IDs to effectively section off a part of the key space, denying service to others in that sector. 

Take a look at @super3's SIP to see how we may solve this in the future: https://github.com/Storj/sips/pull/2

**Comment by littleskunk** [comment]
Idea 1:
Lets generate 100 close nodeIDs and let them run on the same machine. 
Advantage: Only the first and the last node would have to relay the traffic. All other nodes can use localhost for a fast communication. They can send 100 OFFER messages to get the contract.
Disadvantage: Bridge is sending contracts close to the file hash. 100 close nodeIDs will get the same number of contract PUBLISH messages like one nodeIDs.

Idea 2:
Grep the bridge contact list (api.storj.io/contacts) and generate nodeIDs close to other. 3 less and 3 higher nodeIDs and you can isolate the node and get all contract PUBLISH message he would get. Don't relay contract PUBLISH to him or any other node in range. Relay tunnel PUBLISH so that they don't feel isolated. Send 6 OFFER messages and get all contract yourself. Add more nodes if there is a OFFER minimum you need to trigger.

To be continued.

**Comment by bookchin** [comment]
To summarize that SIP, (and @frdwrd may add to this), the idea is to make this kind of attack cost prohibitive by using a distributed reputation system that would have nodes "invest" in their network identity over time and other nodes preferring reputable nodes over others.

**Comment by littleskunk** [comment]
I could generade 100 nodeIDs and use the same payout address for all of them. Hold a few SJCX for reputation and I can start.

How do you detect Idea 2 in order to reduce my reputation? 6 nodeIDs are not a big problem even if I have to pay a little fee for this.

**Comment by bookchin** [comment]
The "reputation" address for the node would be the node ID itself, not a selected address. Each unique node ID is an address itself minus the prefix and checksum.

**Comment by littleskunk** [comment]
Idea 3:
Grep the bridge contact list (api.storj.io/contacts) and calculate the bridge routing table. That steps is only optional. 
3.1 Generate a nodeID to hit bridge bucket 159. Send many FIND_NODE messages to the bridge. Most likely the bridge bucket 159 is full but every FIND_NODE will trigger a PING messages. If one node will not answer with a PONG in time the bridge will remove the node and add my node.
3.2 Generate a nodeID to hit a bridge bucket with a free slot. For this you have to caluclate the bridge routing table. Try to hit a high bucket.

Why that? Because the bridge will send out contracts based on the shard hash. 50% of the hash values will have a 0 or a 1 bit at the beginning. -> 50% of all shards will go to bucket 159. 25% to bucket 158 etc. Depending on the bridge routing table I could place my own nodeID. 20 nodes in bucket 159 but only 5 nodes in bucket 158? 
2.5% of all shards for a place in bucket 159 but 5% for a place in bucket 158. Do the same caluclation for each bucket and you can calculate the best nodeID to get as many contracts as possible.

**Comment by bookchin** [comment]
That particular case will be less relevant when we implement HD keys for nodes. The bridges will have many renter minions with different nodeIDs and thus each one will have a different routing table.

**Comment by frdwrd** [comment]
@super3 has a SIP writeup in progress. A cliffnotes version:

Each nodeID is an ECDSA pubkey, so each node has a bitcoin address, the pubkeyhash. Funds sent to that address can be spent by the owner of the node using the node's private key. 

So attacking any specific neighborhood on the network (eclipse attacks) is already a proof-of-work-type problem: they must create keypairs until they get enough IDs in a certain area, which requires a large amount of computational power. But that doesn't address the attacks above.

Because you can verify that an address belongs to a node using its signature and nodeID, we can create an identity standard that uses the balance and incoming/outgoing transactions to encode information about that node.

We want this system to punish sybil and similar attacks (which consist of many false nodes), while still allowing users to enter the network without any initial investment. Therefore the goal is to make it expensive **over time** for people to operate nodes that aren't providing service to the network. In that way we can bound any such attacks without punishing new real nodes.

Proposal:
A no-burn variation on proof of burn.

Each node that implements this SIP sends their own nodeID's hash (its bitcoin address) a small amount of SJCX every n days/blocks. Nodes that opt in to this SIP prefer to contract with nodes with long, correctly patterned histories of these TXs. The SJCX can be reclaimed by the node, but the payments costs a non-trivial amount of BTC in miner's fees. This payment of the miner's fee represents an investment in that node's identity over time. Nodes making this payment over time have paid, consistently to maintain their ID and their reputation on the network.

Each payment should be small enough to be trivial to people maintaining a single nodeID (much smaller than monthly earnings). But when maintaining nodeIDs, the payments add up. Thus the size and duration of the sybil are bounded by the amount of non-recoupable BTC the attacker is willing to invest in reputation.

Example:
Current counterparty fee is about 0.00034 BTC ($0.20 USD). Alice runs 1 nodeID on a single device making $5.00 monthly. Bob runs 20 nodeIDs on a similar device, gaining more contracts. Alice pays $0.20 monthly to maintain her identity and reputation, but that expense is not significant compared to her income. Bob pays $4.00 monthly to maintain his nodeIDs' reputation. Bob gets additional contracts, but cannot make enough to defray the expense of running those additional nodeIDs. Bob will tone down his nodeIDs. Charlie, an attacker, runs 200,000 nodeIDs, and must pay $40,000 monthly in non-recoupable reputation costs, or all his nodes will be de-prioritized.

Potentially this method could be used to encode other information about a node in the future.

**Comment by frdwrd** [comment]
@bookchin read that over and let me know if my explanation is good. >.>

**Comment by frdwrd** [comment]
Thought: this would also be effective if the nodeID was sending the token away. Coming and going can both be tracked. Might be better if the nodeID is sending the token away, as you can be sure that TX originates with the node.

**Comment by 1credit** [comment]
Hopefully when even contract distribution occurs I'd be able to reduce the number of nodes I'm running from the 40 on one box I do now.  FWIW - typically 4-8 of those nodes are active at any time.  I HAVE TO run multiple nodes if I want to keep the box somewhat busy.  My control for that theory is a single node VM (and my GUIs), which get a fraction of the shards my multi-node machine is getting and often sit for 12+ hours idle.  Just an FYI.

**Comment by frdwrd** [comment]
Yeah, that's one of the things this is looking to address. Limiting the
number of nodes you run on the same hardware.

**Comment by 1credit** [comment]
But need to allow me to optimize for CPU usage.  In theory contract count should do that, but only if I'm contacted... its the original contact that I'm currently optimizing for by having a bunch of nodeids

**Comment by super3** [comment]
Here is the SIP draft: https://github.com/Storj/sips/blob/master/sip-0002.md

@littleskunk Does this help?
@1credit Cost is very low. But enough to make it costly/non-free for an attacker.

**Comment by 1credit** [comment]
Interesting idea but implies I can buy my way to success.  For instance, since I'm a SJCX investor, I could easily send 1000 SJCX to each node and have 1M times the "visibility" of a normal user.  I did not catch the mechanism for having to do this every month though, nor the process for doing the deposit or what happens to the coins once the deposit is made - all of which might negate this argument.

**Comment by super3** [comment]
Like the SIP says this is not considered by itself. Even so it doesn't matter if they have 1 SJCX or 1000 SJCX. Its the SJCX they burn via fees over time that is considered.

**Comment by frdwrd** [comment]
It's not the SJCX that matters, per se, it's the miner's fee paid in BTC while sending them. Paying the fee eats into your profits, which means that the more "fake" nodes you pay a fee for, the less you make. Example: if maintaining each node's identity costs 1% of monthly profits, running 100 nodes on the same hardware makes you break even. But if you run 1000 nodes, you're losing a large amount of money each month. It bounds the size of the attack.

**Comment by 1credit** [comment]
Per the article:  "The farmer may optionally deposit more SJCX for increased visibility.".  My BTC transaction fee would likely be similar if I deposited 0.0001 or 1000 SJCX, would it not?  Presuming so, I'm still concerned about my ability to "buy" visibility.

**Comment by super3** [comment]
Depends 100% renter. Some will take that into account, and others won't.

**Comment by frdwrd** [comment]
I don't necessarily agree that that is a useful feature. There's still a lot of discussion to be done around this. maybe it makes sense to open an issue in the SIPs repo?

**Comment by super3** [comment]
Yup.

**Comment by littleskunk** [comment]
1 is solved. It will be to expensive to pay the fee for 100 or more nodeIDs.

2 is still possible but I need a few moments to calculate it. I will do that later.

Lets focus on 3.1
It is very easy to generate 20 nodeIDs far away from the bridge. All 20 nodeIDs will hit bridge bucket 159. I have to spam everyone else in that bucket to death in order to trigger some PING timeouts. After a few hours I should have full control over bucket 159 and I should be able to regain control if needed. For this attack I need no money because SIP 0002 doesn't effect the p2p comunication. SIP 0002 is starting at the point the Bridge is receiving OFFER Messages.

> It is important that renters not establish contracts based on this identity cost alone. Ideally, they should establish contracts based on established performance, and its relationship with those farmers.
> SIP 0002

Ok I have control over bucket 159 now. Why that? Because the bridge will send 50% of all contracts to my 20 nodeIDs. I will not relay the contracts / relay them only to my own farmer.

This will allow me to pay the fee for only one farmer and get 50% of all shards.

Task that will change the rules:
https://github.com/Storj/core/issues/281
This alone will not solve the problem. If the bridge will take a random minion to send out the contract I could still take over 50% of all shards by taking control over all 159 buckets. In order to stop me the bridge would have to select the minion nodeID close to the shard hash. At that point the bridge would never send any contracts to a 159 bucket and my attack would be complete useless. I would be forced to generate close nodeIDs.

Profiling farmers
I assume that profiling farmers will take care that one nodeID is not allowed to get more than one shard out of the same file. For a 1GB upload I would need more than 1 farmer but at the end still not expencive compared to the 50% shard income.

Micropayment channels:
My 20 nodeIDs would relay cheap contracts to other nodes and I will take 50% of the expensive contracts.

**Comment by littleskunk** [comment]
Update:
I have written a nodeID generator script. I can generate 16 bits in less than 10 minutes. Intel i5-4570 only one core. 20 bits will take a few hours but still possible.

-> Network size of 65,536 - 1,048,576 nodeIDs

New idea 4:
20 nodeIDs far away from the bridge and one bad node. This time we don't spam everyone else in bridge bucket 159. The bad node will help us to disconnect everyone else in order to take over 50% of all shards. The bad node will send out contract PUBLISH messages with an unknown renterID but close to the bad nodeID. This will trigger an endless stream of FIND_NODE messages and the bad node can answer them all. 
Here is the big question: What will happen if the bad node will send an FIND_NODE response including the bridge nodeID with wrong contact information?

**Comment by littleskunk** [comment]
Update:

The bridge has now a HDKey and is running more than one node with different nodeIDs. These nodeIDs are responsible for a tiny segment. No more bucket 159 Uploads.

1 was already solved.

3 is now solved. The bridge will not upload any shards to bucket 159.

4 belongs to #576

2 is still possible as long as the network has not 1,048,576 nodeIDs.

**Comment by bookchin** [comment]
* Item 4 will be resolved with https://github.com/Storj/core/issues/680
* Item 2 is not preventable

Here is a excerpt for the S-Kademlia paper that I think addresses most of the concerns here which should be resolved by the link above:

> **Eclipse attack:**
> This attack tries to place adversarial nodes in the network in a way that one or more nodes are cut off from it, i.e. all messages are routed over at least one adversarial node. This gives the attacker the control over a part of the overlay network. Thus the Eclipse attack can “hide” some nodes from the overlay network. It can be prevented, first, if a node can not choose its nodeId freely and secondly, when it is hard to influence the other nodes routing table. Because Kademlia favors long-living nodes in its k-buckets and nodes are only added, if a bucket is not already full, the latter is easy to achieve as soon as the network has bootstrapped.
> 
> **Sybil attack:**
> In completely decentralized systems there is no instance that controls the quantity of nodeIds an attacker can obtain. Thus an attacker can join the network with lots of nodeIds until he controls a fraction m of all nodes in the network. Douceur [8] proved that this attack can not be prevented but only impeded. In centralized systems one might let nodes pay monetarily to join the network and bind this node to a particular natural person. In completely decentralized systems the only way a node can “pay” only with system resources (bandwidth, CPU power etc.) for authorization.
>
> **Churn attack:**
> If the attacker owns some nodes he may induce high churn in the network until the network stabilization fails. Since a Kademlia node is advised to keep long-living contacts in its routing table, this attack does not have a great impact on the Kademlia overlay topology.

In any case, I would encourage any further discussion to be opened at https://github.com/kadtools/kad
