### ISSUE TITLE
Use Bucket Name for Upload/Download

### ISSUE THREAD

**Issue by super3** [Storj/core#351]
### Expected Behavior

Use the bucket name, or create short aliases that you can use.

```
> storj upload-file "Bucket of Cats" cat.jpg
```

### Actual Behavior

Copy and paste the bucket the bucket id you want to use. 

```
> storj list-buckets
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 5772bc64045f13547c8ae62c, Name:                           Bucket of Cats, Storage: 10, Transfer: 30
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 5772bc93045f13547c8ae64c, Name:                           Database Backups, Storage: 10, Transfer: 30
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 579a75e8ee1e331f0357dcf3, Name:                           cdn, Storage: 10, Transfer: 10
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 57b5ff5732a6f29c1fc8b7e9, Name:                           flood2, Storage: 10, Transfer: 10
> storj upload-file 5772bc64045f13547c8ae62c cat.jpg
```

Looks a little rough when trying to demo:

![https://raw.githubusercontent.com/Storj/core/f2c517199510d10028da8b0944abbbf82148e756/doc/assets/demo.gif](https://raw.githubusercontent.com/Storj/core/f2c517199510d10028da8b0944abbbf82148e756/doc/assets/demo.gif)

**Comment by bookchin** [comment]
Bucket names are not unique, so think of how to handle that. Either way, this should go in bridge.

**Comment by super3** [comment]
### Expected Behavior 
For non-duplicates:
```
> storj upload-file "Bucket of Cats" cat.jpg
```
For duplicates:
```
> storj upload-file "Bucket of Cats" cat.jpg
> Duplicate buckets:
> [1] ID: 5772bc64045f13547c8ae62c, Name: Bucket of Cats, Storage: 10, Transfer: 30
> [2] ID: 5772bc93045f13547c8ae64c, Name: Bucket of Cats, Storage: 10, Transfer: 30
> Enter bucket # or id >
```

@bookchin Since we are not making any changes to bridge, we are only adding an abstraction for the command line tools in core, shouldn't it stay in core?

**Comment by frdwrd** [comment]
@super3 

If you use the name in the CLI, you'd have to preface each upload-file or download-file command with a list-buckets command, or cache the bucket list and risk it being changed by something else and getting desynced.

This belongs in Bridge, because a bridge feature is the only way to do this efficiently.

**Comment by super3** [comment]
If you called the list-bucket command inside the upload command that would
require no changes to bridge, but that's not efficient.

The client just needs to know if it's bucket list is up to date from the
bridge. Anything else should be client side, or we could see lots of errors
in the future with duplicate bucket names.

Will reopen in bridge.

**Comment by NutterzUK** [comment]
How would the bridge be expected to communicate that there is more than one bucket with a given name? Bad request? Then maybe the client knows it needs to do a list-buckets and get the ID?

I'm not convinced this does live in the bridge. The whole point of the ID is that it uniquely identifies a bucket, we surely don't want possibly ambiguous requests going to the bridge which don't specify the exact bucket on which an operation will be performed. 

If we do, aren't we just going to end up with another HTTP request anyway?
Client -> Delete bucket "foo"
Bridge -> "Which foo? 400"
Client -> Ok, get me the bucket IDs
Bridge -> Here are the IDs
Client -> Delete bucket 123.

Is that any better than:
Client -> Get me the bucket IDs
Bridge -> Here are the IDs
Client -> Delete 123

I understand in most cases there may not be multiple buckets with the same names, but personally I think any client which uses the name rather than an ID is the problem of the client. Desyncing shouldn't be a big problem as the user would just get some kinda "Failed: Bucket doesn't exist" kind of message and reload the list of buckets if necessary.

Maybe it could be made a bit more efficient by implementing a "find bucket by name" on the bridge which the client can use to get the ID, which would mean potentially sending less buckets back?

**Comment by bookchin** [comment]
Is this feature really that important to anyone? I think the use of non-unique names to address a bucket creates more problems to solve than the feature is worth.

**Comment by bookchin** [comment]
We should avoid thinking about the API from a end-user perspective. The CLI tool is a reference client interface and is certainly not intended for end-users to upload and download their data. In that way, using a guaranteed unique identifier makes the most sense.

**Comment by super3** [comment]
@bookchin UX is important even in a reference client. People are and will continue to use this tool until something else is available. 

From my perspective yes it is useful:
1) I have written a few tutorials on the reference CLI usage. They most difficult part of the tutorial is trying to show how to use bucket ids. Almost doubles the number of steps to upload, and download data. 
2) I've given and watched @frdwrd give many demos of the reference CLI tools. Its almost guaranteed that we will mistype a bucket id of the course of the demo. I don't believe this would be the case if we could use an alias of the bucket's label.
3) Received feedback from various users while we were doing demos, and they have asked why you can't address the buckets by name. 

Re-opening in bridge, although I think this should be a core only change.
