### ISSUE TITLE
Farmer resync enhancement

### ISSUE THREAD

**Issue by 1credit** [Storj/core#368]
Current core:  3.0.4

Request for enhancement:  Please provide farmer a way to recover missing shards by pulling mirrored copies from the Storj network.  Such a request must not generate any revenue for the farmer.  It would be acceptable if using the remaining networked shards as a backup cost the farmer a small amount of SJCX (and cost effective, if pulling two shards of 2mb each resulted in the saving of a 50GB database).

Two clear advantages of having this feature:

1)  Recovery ability for corrupted or missing shards without loss of the entire database.
2)  Ability to use the Storj network for risk mitigation by the farmer.  For instance, they could use JBOD disk vs. Raid and offer more storage to the network, knowing they could recover from disk failures minimizing their reputation loss.

Additionally:
3)  The concept of using Storj for Storj is rather cool.

One downside:

Recovering an entire disk full of data would take a long time.   For example:  recovering a 4TB drive using 100mbit download link would take approximately 5 days from start to finish IF the sending nodes could, combined, provide 100mbits of upload bandwidth.  During that process reputation loss risk would be mitigated shard-by-shard, IF the farmer was online during the entire process.  That said, farmers might elected to use Raid 5 instead of Raid 6, which would still benefit the community from an available storage protection basis.  This would not be an issue for advantage case #1.

**Comment by littleskunk** [comment]
As renter I have a few problems with this feature.

1.) Farmer can use this to increase traffic payment without loosing shard control. See https://github.com/Storj/core/issues/263

2.) Why should I wait 5 days? I could use different other farmer and recreate the full 4TB in a few minutes. That way I need only 2 or 3 mirrors to be safe. 5 days with only 1 mirror remaining is a problem. This enhancement would force me to create more mirrors and I have to pay them.

As renter I have to vote for No. If you lose my shards I have to repair the lost shards as fast as possible. Waiting 5 days is to risky and expensive for me.

**Comment by 1credit** [comment]
All valid points.  As a farmer however, I would like a way to minimize my reputation loss due to a disk drive failure.  Currently my only option is to utilize raid technology, or backup technology which would be even less efficient (presuming near full space utilization).

Regarding point 1)  My first comment is that this would need to be implemented in some fashion that does not generate increased revenue for the farmer.

Regarding point 2)  By volunteering the fact that a data loss has occurred, prior to the (weekly?) audit figuring it out, I would be increasing the overall protection to the network.  Perhaps a tweek is in order:  If I volunteer that data has been lost and that I'm requesting mirror copies, my node would be given priority over other nodes that may already be involved in covering the gap.  That would not cost the renter a dime, since the system would already be replicating and fixing a bad situation, it would help my reputation (in theory), and would potentially notify the system of the situation earlier than it would auto-discover.

**Comment by littleskunk** [comment]
1.) Lets take a little example. As renter I can give you a shard and myself a mirror of the shard. I will delete my mirror shard asap. Nobody will notice it because only the renter can proof it.
Now its time for some free downloads. I will use my farmer for that. He "lost" the shard and needs a new mirror. Would you please upload your shard to my farmer? Do I have to pay for it or do you upload the shard for free?

2.) I still don't have any advantage as renter. Why not use any farmer? Why should I use you again? Why should I trust you again?

I think the main issue here is the not implemented reputation system. It has to deal with hardware problems in a way that the farmer can regain his reputation in a few days or weeks. I agree with that but I don't think the farmer needs 5 days and his old shards for this. Why not farm new shards? You will get the lost shards of other farmer as well. It should be fair for every farmer.

**Comment by 1credit** [comment]
For the sake of my reputation, I would be willing to pay to copy the mirrors.  Remember that 5 days (using a hopefully worst case of a full 4TB disk) is for the very last shard.  I would have 50% of those restored in 2.5 days, 25% in 30 hours, 5% in 6 hours - well WELL before any audit would likely catch things and spawn an automatic free copy.

**Comment by littleskunk** [comment]
Ok now we have an agreement. If you pay for the lost shard I will give you the shard again. That way I get a new copy without any payment from my side. Yes that could work for farmer and renter.

**Comment by 1credit** [comment]
Overall, I should still be ahead.  Using a typical 8 drive Raid 6 set I could offer 32GB of JBOD space instead of 24GB of Raid protected should 1 or 2 drives fail.   If 3 or more fail, I would just have to take the reputation hit, and deserve it.

**Comment by super3** [comment]
Closing this for the following reasons:

1) The potential for abuse of this is too high. While hard drive failures do occur though no fault of the renter, they should either add physical redundancy or take the hit on reputation. I have always recommended taking the hit, as taking the chance on failure should have more earning potential than physical redundancy. 
2) The avoid abuse the farmer would have to have the ability to pay other farmers, and that feature is a long way off.
3) The renter has little to no incentive to do this. Lets say the farmer is storing 4 TB, and it has a failed drive. It is orders of magnitudes quicker to distribute to other farmers because the recover process is bottlenecked by the failed farmers connection. 
4) This operation exposes the alternate locations of the files, something that we don't wish to expose for the privacy for renter and the farmer. This is information that only the renter should know.
5) This would be mostly incompatible with a Reed-Solomon redundancy method.
