### ISSUE TITLE
Using HTTP vs raw TCP streams vs Websocket for JSON-RPC messages

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#490]
### Discussion
After spending some time trying to reduce the number of incoming and outgoing connections between storj share nodes, I can't quite understand the reason for using HTTP as a transport in the kad library. Is there an actual use case for the HTTP transport other than sending JSON-RPC messages back and forth?

If HTTP is only being used to transport JSON-RPC messages, then why not simply remove the overhead of HTTP and set up one stream socket between nodes and let JSON-RPC provide the message encapsulation as intended. This could be accomplished with a simple TCP socket or, if HTTP might be used in the future for some other form of communication other than the JSON-RPC messages, then perhaps upgrade the connection with a Websocket stream.

If we could get the number of connections between two nodes down to one or two persistent TCP connections that would significantly reduce the network overhead required to run a storj share. It is my belief that the signaling protocol layer of the storj network should be the least intensive part of the network, yet from what I can tell it currently requires more resources than the actual shard data transfer layer.

What does everyone think?

Also if we could hear the original reasons for choosing the HTTP transport that would be helpful. I can see that when interfacing with renters HTTP is a good quick and easy choice, but when we have long term connections established between share nodes it makes more sense to me to use something like Websockets instead. I see that Websockets are used for tunneling, so why not use them for long term node to node communications as well?

**Comment by bookchin** [comment]
* HTTP was chosen as the RPC transport to make Storj "web-first" (it's possible to run a full node from within the browser without a proxy layer or browser extension)
* WebSockets are not used for RPC communication because nodes exchange small messages with *many* other nodes - leaving long lived connections opened with many nodes has significant drawbacks
* Kademlia implements a structured network and messages are not routed/relayed ad-hoc by other nodes - you will always communicate directly to the target (unless you are tunneled)
* The problem you are seeing now is related to the DDoS, nodes are accepting a large number of connections faster than they can be processed and closed - the bridge new releases address this and you should see significant improvements there soon

**Comment by yuilleb** [comment]
Thanks for replying @bookchin! That's so cool that it can run from the browser. I did not know this, so that makes perfect sense why you'd pick HTTP at least as the main transport.

I suppose based on the traffic patterns I saw I assumed the network layout was more like that of Bitcoin. I see lots of continuous communication between myself and a handful of nodes, so I assumed they were relaying messages between each other and this immediately made me think it could be improved with persistence. I obviously have more reading to do.

> WebSockets are not used for RPC communication because nodes exchange small messages with many other nodes - leaving long lived connections opened with many nodes has significant drawbacks

Can you elaborate? Does this mean you'd advise against even enabling HTTP keep-alive for reusing connections?

**Comment by jackyq2015** [comment]
I think node "connected for a long time" and "long lived connection" is completely different things. Though I agree that the DDos is a big problem for storj share. I stopped my node few days ago since I don't want my box busy for nothing. I took some time to filter out the bad nodes. But I don't think it's a task need to be taken care of from the worker node level. The bridge expose all the information for exploit but does not designed to safeguard the Kademlia network. It may not be a issue of the bridge but it is Kademlia by design. Establishing a long lived connection might be a cure, but how about a bad node still have a way to connect you and flood you.

**Comment by bookchin** [comment]
@yuilleb it's true that nodes communicate more frequently with their neighbors, so we could modify the transport adapter to create persistent connections to its nearest neighbors. It may not be trivial task though, since each node's routing table won't always be "symmetric" in that one Alice's N neighbors may not always include Bob, even if Bob has Alice as one of his nearest neighbors, so we'd need to invent some algorithm for coordinating those "allowed" persistent connections. 

Overall, I think it's a smart approach to do something like this, but I think it needs some thought and discussion around the coordination and protocol aspect.

**Comment by bookchin** [comment]
I suspect that the recent fixes will make this more of a topic of optimization rather than a critical change to the transport logic.

**Comment by yuilleb** [comment]
@bookchin I hope you're right and I know you would definitely know more about what's causing these problems than I would. Originally I was trying to help another user solve their connection problems and in doing so I started to wonder why don't we cut down on all these connections (multiple connections to the same hosts) that are mostly being setup sending one RPC message and then sitting there idle until timeout? This user in specific was reporting packet loss at their modem, and it seems related to the number of simultaneous connections being made rather than bandwidth utilization. It made me think rather than setting up 10 separate connections why not just use the 1 original connection to send the 10 JSON-RPC messages down it? Doing something like this uses less bandwidth and less overall network resources.

But yeah you might be right that whatever fix you're working on the bridge front might reduce the signalling traffic that this then becomes a non existent issue. So it's probably best to wait for that fix to take place to see if there's a reason to go further with this discussion. I'm glad you're thinking about it though and if using something like websockets between neighbors looks like a good idea I'm happy to help write that code. In such a case I'm not sure it matters if Alice sends her traffic down a websocket to Bob, while Bob sends his requests over vanilla HTTP. As long as we make the websocket json-rpc as an optional channel then all should be fine I would think.

Also do you see a problem with using HTTP keep-alive for reusing HTTP connections? I submitted a [pull request](https://github.com/kadtools/kad/pull/73) about that, but the biggest problem I know of is older versions of Node.js simply do not work due to an internal bug so the client automatically closes the connection no matter if keep-alive was enabled. I can't figure how this could hurt, but you did mention you thought "leaving long lived connections opened with many nodes has significant drawbacks". Can you elaborate on that?

Sorry I know this is quite lengthy.

**Comment by yuilleb** [comment]
@jackyq2015 What you describe is something that worries me. I've noticed many users are coming up with interesting ways of using iptables to rate limit the number of connections to/from other nodes. This right here was a big reason why I started to wonder about setting up dedicated persistent streams for RPC messages. What you describe as filtering out the "bad nodes" is quite funny as people were looking at my high traffic node as if it was bad and were intentionally blocking it to protect their node. My node however was sending valid traffic, which means they were simply blocking legit network traffic. I think storj is likely to have a tough time growing the network if the average user is getting hammered with traffic like we're seeing now.

Now if you are really concerned about a real "bad" actor trying to hammer your network, they won't be doing it with legitimate outbound tcp connections (like we are seeing now) as that is expensive to their own internal network resources more so than yours. A bad actor is more likely to target sending you messages that cause your node to do lots of work (dos) or cause you to send out more data than they originally sent (amplification).

**Comment by jackyq2015** [comment]
@yuilleb Sometime maybe it's good nodes but do the bad things. It is hard to tell. But if I found there's one IP keep initializing the connections(say 30 connections) but there is no contract, I will block it. There were few times I checked the log to see what's going on. Most of time I just don't have patience. The results turned out I could get some contract afterward.
