### ISSUE TITLE
Enhancement: Attempt compression before encrypting

### ISSUE THREAD

**Issue by yuilleb** [Storj/core#529]
Based on [simple tests done from here](https://github.com/Storj/kfs/issues/33#issuecomment-254720275) it would make sense to attempt compressing files before encrypting.

I would think it wise to have compression enabled by default, but have flags to control it along with possibly changing the compression scheme. It would also be necessary to store the compression scheme used with the file's meta data.

**Comment by bookchin** [comment]
This package does not enforce any encryption or compression at all by default. Both of those choices are up to the implementing client (in this case, probably `storj-cli`). That said, I don't think it makes sense to add any code for managing compression configuration at either layer, since it's use-case specific.

My position is that if you want your data compressed before encryption, then compress it with the tool of your choice.
