### ISSUE TITLE
Send probe message to check manual port forwarding

### ISSUE THREAD

**Issue by littleskunk** [storj/core#535]
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.6.0
```
### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

I have a bad config. I set a puplic ip but missed the port forwarding. I would like to get an error message. Sending a probe to any other node would be nice.

**Comment by bookchin** [comment]
@littleskunk did you set `doNotTraverseNat` to `true`? If you leave it `false`, then it should send PROBE and if it fails you should know about it.

**Comment by littleskunk** [comment]
Not all user are able to open a port. The idea of this issue was to use it as default or even as recommended setting. At the moment that is not possible because PROBE will sometimes report false negatives. The port is open but the other farmer for the PROBE message is offline. If we could remove these false negatives it would be perfect.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
