### ISSUE TITLE
contract topic add upload interval

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#56]
As farmer I would like to get backup contracts. I can fill my drive in 20 days but I need 100 days to upload everything (50MBit/s down and 10MBit/s upload).
I can offer ~10MBit/s fullspeed as long as my contracts are using my drive for backups and wait more than 100 days to download them.

On the other side a farmer with only 1TB and 100MBit/s upload would like to get farmer that wait less than 1 day to download them.

An upload interval filter would allow both farmer to get max profit. Both can fill there complete drive and use there upload traffic. At the moment they will get mixed contracts. Farmer 1 will end up with an empty drive and farmer 2 will never be able to max his upload traffic.

Edit: For the renter it would be a download interval. I guess you will find a better name and a good scal.

**Comment by gordonwritescode** [comment]
I think this might just be as simple as setting the existing parameters for `payment_storage_price` and `payment_download_price` to promote this behavior in the contract.

Backup farmer would make offers on contracts with a low storage price but expensive download price to make it cost prohibitive to download the data sooner or more often than needed. Conversely, the other farmer in your example might set a higher storage price (due to space limitations), but set a low download price to encourage renters to store small frequently accessed data.

Do you really think we need a new contract property or set of properties to be more explicit? I tend to think the economics win here.

**Comment by littleskunk** [comment]
You are right. That should work. Thank you :)
