### ISSUE TITLE
UPnP optain dynamic ip change

### ISSUE THREAD

**Issue by littleskunk** [storj/core#600]
As farmer I would like to use the storjshare GUI or CLI default config (127.0.0.1 and use UPnP). Every 24 hours my ISP gives me a new external ip. Please use UPnP again to obtain my new external ip and update my contact information. This will allow me to keep my node online without restarting it every 24 hours.

**Comment by littleskunk** [comment]
Workaround for UPnP user with dynamic external ip:
Restart GUI / CLI once every 24 hours. If possible scheduled a few minutes after ISP external address change.
OR
Setup manual port forwarding and use dyndns. Even if we optain your new dynamic IP you will have a few minutes downtime. Dyndns is able to reduce this to a few seconds downtime. It is the prefered solution even if we implement a slution that works with upnp.

**Comment by MeijeSibbel** [comment]
https://docs.storj.io/v1.1/discuss/59b7b4a348ee6b0026e782ee

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
