### ISSUE TITLE
Error trying to restart farmer client.

### ISSUE THREAD

**Issue by subwolf** [Storj/core#67]
### Package Versions

Replace the values below using the output from `npm list storj`.

```
/root
└─┬ storj-farmer@2.1.1
  └── storj@0.5.2 
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
On Synology NAS where behaviour may be very different. Just starting program again - had run before with no problems, expected tunnel to be established and to continue.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"sending PROBE message to {\"protocol\":\"0.6.7\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461970254213}","timestamp":"2016-04-29T22:50:54.213Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-29T22:50:55.419Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Failed to load the shard metadata
    at /usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapters/fs.js:145:25
    at /usr/local/lib/node_modules/storj-farmer/node_modules/storj/lib/storage/adapters/fs.js:301:14
    at FSReqWrap.oncomplete (fs.js:82:15)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run the program, Ctrl-C to end while running.
2. Start program again, observe.
3. ...

Note: When I try to npm install, this is what I see:
```
root@subwolf-nas:~# npm install -g storj-farmer
/usr/local/bin/storjfarm -> /usr/local/lib/node_modules/storj-farmer/bin/farmer.js
storj-farmer@2.2.6 /usr/local/lib/node_modules/storj-farmer
├── async@1.5.2
├── colors@1.1.2
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── bs58@3.0.0 (base-x@1.0.4)
├── kad-logger-json@0.1.2 (readable-stream@2.1.2, chai@3.5.0)
├── myspeed@1.0.2 (hat@0.0.3, ws@1.1.0, timer-stopwatch@0.2.0, noisegen@1.0.0)
├── prompt@1.0.0 (revalidator@0.1.8, pkginfo@0.4.0, read@1.0.7, winston@2.1.1, utile@0.3.0)
└── storj@0.6.7 (ms@0.7.1, merge@1.2.0, ip@1.1.2, mtree@0.0.1, bitcore-message@1.0.2, semver@5.1.0, readable-stream@2.1.2, ws@1.1.0, bitcore-ecies@1.0.1, json-stable-stringify@1.0.1, jsen@0.6.1, kad-quasar@0.1.0, nat-upnp@1.0.0, request@2.72.0, kad@1.5.5, bitcore-lib@0.13.15)
```

**Comment by subwolf** [comment]
Made sure both local and global versions are the latest, same error on start.

**Comment by gordonwritescode** [comment]
Hey dude, thanks for the report. Can you `ls -R /path/to/sharddir` and paste that here?

**Comment by subwolf** [comment]
Due to the other issue I created the directory is currently empty.

**Comment by gordonwritescode** [comment]
I haven't been able to reproduce this until today some tests fail nondeterministically with this error, causing a cascade of other failures. 

I think I have enough information to find the problem. Stand by.

**Comment by gordonwritescode** [comment]
Okay, I think I know what's going on here. 

1. This happened: https://github.com/Storj/core/issues/68 while we were trying to write the shard metadata, causing the file to be incomplete/corrupted
2. When you restart your farmer, the shard reaper runs and tries to load each contract+metadata to determine if the contract is expired
3. As a result, this throws https://github.com/Storj/core/blob/master/lib/storage/adapters/fs.js#L289 because the shard metadata file is bad

I've noticed this manifests in the tests from time to time as a race condition, where the test renter tries to retrieve a shard from the farmer it *just* negotiated a contract with and the farmer isn't finished writing the metadata file (which is actually just empty `{}` right now).

The quick solution here is to be fault tolerant when parsing the shard metadata - if the data is corrupted or incomplete or invalid, we can just return `{}` - which may suffice longer term as well since an empty metadata object is better than a broken one that crashes the program. 

Ultimately, what **should** be done is to ensure that the writes complete before doing anything else. This is as easy as doing the writes synchronously, but I worry about performance and blocking network I/O during shard reaping. Will give it some thought and issue a fix and release today.

**Comment by gordonwritescode** [comment]
*Actually*, I think we could avoid the shard reaping I/O issue by doing asynchronous reads and synchronous writes.
