### ISSUE TITLE
Port shows as closed when NAT reflection is blocked in firewall

### ISSUE THREAD

**Issue by ssa3512** [storj/core#703]
### Package Versions

`storj-lib@6.6.0`
`node version v6.10.3`

### Expected Behavior

When a user has opened a port and it is accessible via the outside (shows open via external tool such as yougetsignal.com, canyouseeme.org, storjstat.com, etc storj-lib should set _portOpen to true in the transport, so this can be reflected on daemon and gui.

### Actual Behavior

storj-lib is setting _portOpen to false if it is not able to connect to itself via the external IP or address set in config as it is using _checkIfReachable to determine if the port is open. The daemon and gui then show the port as closed when it is in fact opened.

### Steps to Reproduce

1. Forward node port as per Storjshare configuration instructions
2. Configure firewall with `NAT reflection` or `NAT loopback` setting disabled
3. Port shows as `closed` in daemon and gui. `_portOpen` is set to false in `transport.js` when `_open` is called.

**Comment by luzemario** [comment]
I temporarily resolve this using split DNS. Since I have a pfSense box as router, I followed the directions from [https://doc.pfsense.org/index.php/Why_can%27t_I_access_forwarded_ports_on_my_WAN_IP_from_my_LAN/OPTx_networks](url), and set a internal DNS entry pointing the external domain back to my storjshare box. Any setup using a internal router as DNS resolver can use this "hack". You can add a entry for <yourhost>.no-ip.org for example, to IP 192.168.X.Y (the internal address of your storjshare box), then make your storjshare box use this router as DNS provider.

After issuing a "storjshare-restart -a", it shows the port as open.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
