### ISSUE TITLE
Feature Request: Nextcloud & Owncloud Support

### ISSUE THREAD

**Issue by sunjam** [storj/core#710]
[Congrats on the partnership with FileZilla](http://blog.storj.io/post/163215547738/storj-and-filezilla-integration-bringing)!  I'm wondering about accessing Storj from within [Nextcloud](https://github.com/nextcloud/server) or [Owncloud](https://github.com/owncloud/core).  Those projects support a variety of storage protocols and can be expanded through [3rd party apps.](https://apps.nextcloud.com/)

You already have a lot on your plate, but it would be great to see these decentralized applications paired up!

**Comment by MeijeSibbel** [comment]
https://github.com/lakewik/storj_gui_client/releases/tag/0.1.9.1

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
