### ISSUE TITLE
Deny unpaid mirror creation

### ISSUE THREAD

**Issue by littleskunk** [storj/core#719]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
└─┬ storjshare-daemon@3.5.4
  └── storj-lib@6.7.0
```

Replace the values below using the output from `node --version`.

```
v6.11.2
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Farmer should not be able to deny unpaid mirror traffic, not see the difference between unpaid and paid traffic or should get a payment for mirror traffic.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

libstorj is sending additional header informations. That way the farmer can detect paid downloads and deny them. No more mirror creation and 100% download traffic.

Removing the header informations will not help. There are still other ways to detect unpaid mirror traffic.

**Comment by littleskunk** [comment]
Best option could be a tiny payment for mirror creation. All 5 mirrors are created at the beginning. I am not able to predict if that shard will generate high or low download traffic. I have to assume it is a low download traffic shard and take the additional mirror payment even if it is very low.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
