### ISSUE TITLE
Speed test of myspeed and iperf on a 10Gbit/s network

### ISSUE THREAD

**Issue by Th3Van** [Storj/core#72]
This is not a bug, but more a heads up on how myspeed and iperf speed test preforms on a Cisco Nexus 10Gbit/s network.
I assume that myspeed are still being developed, so we should see updated and faster versions in the future?

[Storj - Myspeed and Iperf.txt](https://github.com/Storj/core/files/243952/Storj.-.Myspeed.and.Iperf.txt)

Regards,
Th3van

**Comment by gordonwritescode** [comment]
Yes, the myspeed module was hacked to gather very quickly and needs love. Right now the bottleneck is probably how quickly the CPU can churn out random bytes. We should be using static files of different sizes to get a more accurate test of bandwidth instead of generating random bytes on demand. 

Would you mind opening an issue here: https://github.com/gordonwritescode/myspeed/issues

**Comment by gordonwritescode** [comment]
I'm going to close this one, since ultimately this will be handled outside of core.
