### ISSUE TITLE
"payment_download_price">0,

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/core#729]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@6.0.3/home/gordon/Code/storj-bridge
└── Storj share GUI v6.4
```

Replace the values below using the output from `node --version`.

```
Storj Share GUI v6.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
No errors 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"debug","message":"contact already in bucket, moving to tail","timestamp":"2017-09-17T10:40:06.185Z"}
{"level":"debug","message":"checking pending rpc callback stack for 109230c9e0d60e491e01557d571c6c7858aa9f08","timestamp":"2017-09-17T10:40:06.188Z"}
{"level":"info","message":"Offer accepted","timestamp":"2017-09-17T10:40:06.222Z"}
undefined:1
{"hash":"d3f14edd21d1f436216e3f4e97457981f2c835e0","fskey":"b00869b921d09af52c6bce53dee0e058bdc4acbc","shard":null,"contracts":{"d5ef87534665b03d6ebaff22e71859a12b7b6701":{"audit_count":4,"data_hash":"d3f14edd21d1f436216e3f4e97457981f2c835e0","data_size":8,"farmer_id":"d666f5a3675ffb6b0fecaacdc39b06d3ea05279b","farmer_signature":"H97xQ/NkZRnqZxobQ5rc1u8tl2AzRyjLCLVedyKzNbfeaiCal626Ixc/JhmUkTjft6BH094PJ65Z6q0eO2Z9Rmk=","payment_destination":"0xF489e41a21B824cc5385cA39560146EA2aC9D5d3","payment_download_price">0,"payment_storage_price":0,"renter_hd_index":142,"renter_hd_key":"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42","renter_id":"d5ef87534665b03d6ebaff22e71859a12b7b6701","renter_signature":"ILBw9vN94YAOUIkGQZBo6EPbZ/lJ459jrOoTTMYbNO4Vbx3SqmpRrSNzRCl+UXYDAsU7D2xajM/rKnZUFPafwxY=","store_begin":1500563011343,"store_end":1508339011343,"version":0}},"challenges":{},"trees":{},"meta":{"d5ef87534665b03d6ebaff22e71859a12b7b6701":{}},"

SyntaxError: Unexpected token > in JSON at position 513
at JSON.parse (<anonymous>)
at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:110:25
at C:\Program Files\Storj Share\resources\app\node_modules\levelup\lib\levelup.js:236:7
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
