### ISSUE TITLE
Set farmer base payout requirement to 7300GB/h to avoid cheaters 

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/core#737]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by braydonf** [comment]
This isn't the correct place for this, as there isn't any payout code here.

**Comment by MeijeSibbel** [comment]
Is there a correct github repo where we can open this issue instead?, i haven't found it. Maybe open a "farmer-payouts" repo, so that we can open issues about farmer payouts there.

**Comment by mstuehlinger** [comment]
The propsed increase of the GBh threshold would not prevent the majority of base payout "abuser" observed in September. Most of them qualified through downloadedBytes > 0.

Would the [PayoutFormula Gist](https://gist.github.com/pgerbes1/8c0bdfc70055786cec43b885af5b249f) be the right place to discuss this?

**Comment by akostadinov** [comment]
Perhaps explain how current cheating works and how proposal will fix it. Personally I'm bugged that I'm running a node for a week and have less than 100MB files stored.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
