### ISSUE TITLE
filenames not deleted after contracts end

### ISSUE THREAD

**Issue by marcorosa** [storj/core#762]
### Package Versions

```
storjshare-daemon@5.3.0
storj-lib@8.6.0 
```

### Expected Behavior

Once contracts expire, and are not renewed, files are deleted (they are supposed to disappear completely from the bucket).

### Actual Behavior

Shards are deleted but file names are not.
I have a lot of buckets with a lot of files that are not accessible anymore, but their name is still there.
Implementing renewal of contracts will not fix this, because if a user does not pay for storage space, only shards will deleted, whereas filenames will remain available inside buckets.
At this moment, a filename (that can be a very long string) could be exploited for storing data for free (and forever?).

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
